### ISSUE TITLE
Missing context menu

### ISSUE THREAD

**Issue by maxkolenko** [BlackGlory/copycat#48]
Context menu is missing until the extension is toggled off and on again in Firefox 114.0.2 on Windows. This behavior has been observed for several months already.

**Comment by BlackGlory** [comment]
Consider that Copycat's context menu has been working correctly for at least two years (the last version of Firefox was released 3 years ago) and has always worked correctly in Chrome. I can only think this is a Firefox bug, and I'm afraid there is no non-hack way to fix it.

Here's the code related to the context menu:
https://github.com/BlackGlory/copycat/blob/7c7a865ad7b7125c25ef653a4ff95ce204bb95ca/src/background/index.ts#L68-L79

**Comment by maxkolenko** [comment]
I've moved to MacOS with Firefox 119 and the issue is there as well. I understand that there're Firefox bugs but other extensions somehow manage to show consistently their entries in the contex menu. I hope there's a solution for this issue in this great extension. I've tried to move to alternative extensions but Copycat is the best.

**Comment by BlackGlory** [comment]
Just tried to solve this problem and sadly found that debugging the relevant behavior of the extension is not possible in the latest version of Firefox:
- Temporarily loaded extensions will be deleted after restarting Firefox.
- Installing self-packaged extensions is not possible, one of the following two errors will pop up:
   - "This add-on could not be installed because it appears to be corrupt."
   - "This add-on could not be installed because it has not been verified."

Years later, Firefox extension development experience is still the worst, I guess I can only debug by submitting a new version (very stupid), I don't want to continue wasting time on this.

**Comment by BlackGlory** [comment]
So I haven't given up yet.
It took me 20 minutes to figure out how to sign my extension without submitting a new version.

I think the problem might be related to https://github.com/BlackGlory/copycat/blob/7c7a865ad7b7125c25ef653a4ff95ce204bb95ca/src/manifest.json#L62

**Comment by BlackGlory** [comment]
v2.4.6 has just been released, which should solve this problem.
