### ISSUE TITLE
Why permission "See browsing history" in Chrome?

### ISSUE THREAD

**Issue by angularsen** [BlackGlory/copycat#7]
This seems a bit intrusive for a copy-link feature, why is this needed?

**Comment by BlackGlory** [comment]
It is permission "tabs", [the "tabs" permission is required in order to populate the url, title, and favIconUrl properties of Tab](https://developer.chrome.com/extensions/tabs), some features require it.

I think Chrome's tips are misleading, maybe I should explain the role of each permission in the description of the next version.

**Comment by angularsen** [comment]
Thanks for clarifying 👍 
Yes Chrome's permissions are awfully broad and generic :-/

**Comment by angularsen** [comment]
I wish Chrome had a more on-a-need-basis permission, granting certain permissions only when you want to use a particular feature or for a certain page - or when actively interacting with a Chrome plugin.
