### ISSUE TITLE
Percent encode parenthesis in URL when creating Markdown link

### ISSUE THREAD

**Issue by leesei** [BlackGlory/copycat#9]
URL: https://www.wikiwand.com/en/Ring_(mathematics)
"Tab link -> Markdown":
`[Ring (mathematics) - Wikiwand](https://www.wikiwand.com/en/Ring_(mathematics))`
which caused problem in some Markdown parser

I recommends outputting this:
`[Field (mathematics) - Wikiwand](https://www.wikiwand.com/en/Field_%28mathematics%29)`

**Comment by leesei** [comment]
Also encode space as `%20`

**Comment by BlackGlory** [comment]
This issue is more complicated than I thought.
I found that brackets are explicitly listed as reserved characters in the URL encoding.
A Markdown parser should have the ability to distinguish between URLs and Markdown syntax,
and if it can't, then it needs to be fixed.
This extension should not change the output for this particular case.
